-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.10.0.111.2
-- Module  Version: 5.8
--/usr/local/diamond/3.10_x64/ispfpga/bin/lin64/scuba -w -n adc_driver -lang vhdl -synth lse -bus_exp 7 -bb -arch sa5p00 -type iol -mode Receive -io_type LVDS -width 12 -freq_in 200 -gear 2 -del 128 -fdc /home/rjordans/SurfDrive/Projects/RadboudRadioLab/Auger/auger-radio-extension/rtl/adc_driver/adc_driver.fdc 

-- Wed Oct 31 12:12:24 2018

library IEEE;
use IEEE.std_logic_1164.all;
library ECP5U;
use ECP5U.components.all;

entity adc_driver is
    port (
        clkin: in  std_logic; 
        reset: in  std_logic; 
        sclk: out  std_logic; 
        datain: in  std_logic_vector(11 downto 0); 
        q: out  std_logic_vector(23 downto 0));
end adc_driver;

architecture Structure of adc_driver is

    -- internal signal declarations
    signal buf_clkin: std_logic;
    signal qb11: std_logic;
    signal qa11: std_logic;
    signal qb10: std_logic;
    signal qa10: std_logic;
    signal qb9: std_logic;
    signal qa9: std_logic;
    signal qb8: std_logic;
    signal qa8: std_logic;
    signal qb7: std_logic;
    signal qa7: std_logic;
    signal qb6: std_logic;
    signal qa6: std_logic;
    signal qb5: std_logic;
    signal qa5: std_logic;
    signal qb4: std_logic;
    signal qa4: std_logic;
    signal qb3: std_logic;
    signal qa3: std_logic;
    signal qb2: std_logic;
    signal qa2: std_logic;
    signal qb1: std_logic;
    signal qa1: std_logic;
    signal qb0: std_logic;
    signal qa0: std_logic;
    signal sclk_t: std_logic;
    signal dataini_t11: std_logic;
    signal dataini_t10: std_logic;
    signal dataini_t9: std_logic;
    signal dataini_t8: std_logic;
    signal dataini_t7: std_logic;
    signal dataini_t6: std_logic;
    signal dataini_t5: std_logic;
    signal dataini_t4: std_logic;
    signal dataini_t3: std_logic;
    signal dataini_t2: std_logic;
    signal dataini_t1: std_logic;
    signal dataini_t0: std_logic;
    signal buf_dataini11: std_logic;
    signal buf_dataini10: std_logic;
    signal buf_dataini9: std_logic;
    signal buf_dataini8: std_logic;
    signal buf_dataini7: std_logic;
    signal buf_dataini6: std_logic;
    signal buf_dataini5: std_logic;
    signal buf_dataini4: std_logic;
    signal buf_dataini3: std_logic;
    signal buf_dataini2: std_logic;
    signal buf_dataini1: std_logic;
    signal buf_dataini0: std_logic;

    attribute IO_TYPE : string; 
    attribute IO_TYPE of Inst3_IB : label is "LVDS";
    attribute IO_TYPE of Inst1_IB11 : label is "LVDS";
    attribute IO_TYPE of Inst1_IB10 : label is "LVDS";
    attribute IO_TYPE of Inst1_IB9 : label is "LVDS";
    attribute IO_TYPE of Inst1_IB8 : label is "LVDS";
    attribute IO_TYPE of Inst1_IB7 : label is "LVDS";
    attribute IO_TYPE of Inst1_IB6 : label is "LVDS";
    attribute IO_TYPE of Inst1_IB5 : label is "LVDS";
    attribute IO_TYPE of Inst1_IB4 : label is "LVDS";
    attribute IO_TYPE of Inst1_IB3 : label is "LVDS";
    attribute IO_TYPE of Inst1_IB2 : label is "LVDS";
    attribute IO_TYPE of Inst1_IB1 : label is "LVDS";
    attribute IO_TYPE of Inst1_IB0 : label is "LVDS";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    Inst3_IB: IB
        port map (I=>clkin, O=>buf_clkin);

    Inst2_IDDRX1F11: IDDRX1F
        port map (D=>dataini_t11, SCLK=>sclk_t, RST=>reset, Q0=>qa11, 
            Q1=>qb11);

    Inst2_IDDRX1F10: IDDRX1F
        port map (D=>dataini_t10, SCLK=>sclk_t, RST=>reset, Q0=>qa10, 
            Q1=>qb10);

    Inst2_IDDRX1F9: IDDRX1F
        port map (D=>dataini_t9, SCLK=>sclk_t, RST=>reset, Q0=>qa9, 
            Q1=>qb9);

    Inst2_IDDRX1F8: IDDRX1F
        port map (D=>dataini_t8, SCLK=>sclk_t, RST=>reset, Q0=>qa8, 
            Q1=>qb8);

    Inst2_IDDRX1F7: IDDRX1F
        port map (D=>dataini_t7, SCLK=>sclk_t, RST=>reset, Q0=>qa7, 
            Q1=>qb7);

    Inst2_IDDRX1F6: IDDRX1F
        port map (D=>dataini_t6, SCLK=>sclk_t, RST=>reset, Q0=>qa6, 
            Q1=>qb6);

    Inst2_IDDRX1F5: IDDRX1F
        port map (D=>dataini_t5, SCLK=>sclk_t, RST=>reset, Q0=>qa5, 
            Q1=>qb5);

    Inst2_IDDRX1F4: IDDRX1F
        port map (D=>dataini_t4, SCLK=>sclk_t, RST=>reset, Q0=>qa4, 
            Q1=>qb4);

    Inst2_IDDRX1F3: IDDRX1F
        port map (D=>dataini_t3, SCLK=>sclk_t, RST=>reset, Q0=>qa3, 
            Q1=>qb3);

    Inst2_IDDRX1F2: IDDRX1F
        port map (D=>dataini_t2, SCLK=>sclk_t, RST=>reset, Q0=>qa2, 
            Q1=>qb2);

    Inst2_IDDRX1F1: IDDRX1F
        port map (D=>dataini_t1, SCLK=>sclk_t, RST=>reset, Q0=>qa1, 
            Q1=>qb1);

    Inst2_IDDRX1F0: IDDRX1F
        port map (D=>dataini_t0, SCLK=>sclk_t, RST=>reset, Q0=>qa0, 
            Q1=>qb0);

    udel_dataini11: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini11, Z=>dataini_t11);

    udel_dataini10: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini10, Z=>dataini_t10);

    udel_dataini9: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini9, Z=>dataini_t9);

    udel_dataini8: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini8, Z=>dataini_t8);

    udel_dataini7: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini7, Z=>dataini_t7);

    udel_dataini6: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini6, Z=>dataini_t6);

    udel_dataini5: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini5, Z=>dataini_t5);

    udel_dataini4: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini4, Z=>dataini_t4);

    udel_dataini3: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini3, Z=>dataini_t3);

    udel_dataini2: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini2, Z=>dataini_t2);

    udel_dataini1: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini1, Z=>dataini_t1);

    udel_dataini0: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini0, Z=>dataini_t0);

    Inst1_IB11: IB
        port map (I=>datain(11), O=>buf_dataini11);

    Inst1_IB10: IB
        port map (I=>datain(10), O=>buf_dataini10);

    Inst1_IB9: IB
        port map (I=>datain(9), O=>buf_dataini9);

    Inst1_IB8: IB
        port map (I=>datain(8), O=>buf_dataini8);

    Inst1_IB7: IB
        port map (I=>datain(7), O=>buf_dataini7);

    Inst1_IB6: IB
        port map (I=>datain(6), O=>buf_dataini6);

    Inst1_IB5: IB
        port map (I=>datain(5), O=>buf_dataini5);

    Inst1_IB4: IB
        port map (I=>datain(4), O=>buf_dataini4);

    Inst1_IB3: IB
        port map (I=>datain(3), O=>buf_dataini3);

    Inst1_IB2: IB
        port map (I=>datain(2), O=>buf_dataini2);

    Inst1_IB1: IB
        port map (I=>datain(1), O=>buf_dataini1);

    Inst1_IB0: IB
        port map (I=>datain(0), O=>buf_dataini0);

    sclk <= sclk_t;
    q(23) <= qb11;
    q(22) <= qb10;
    q(21) <= qb9;
    q(20) <= qb8;
    q(19) <= qb7;
    q(18) <= qb6;
    q(17) <= qb5;
    q(16) <= qb4;
    q(15) <= qb3;
    q(14) <= qb2;
    q(13) <= qb1;
    q(12) <= qb0;
    q(11) <= qa11;
    q(10) <= qa10;
    q(9) <= qa9;
    q(8) <= qa8;
    q(7) <= qa7;
    q(6) <= qa6;
    q(5) <= qa5;
    q(4) <= qa4;
    q(3) <= qa3;
    q(2) <= qa2;
    q(1) <= qa1;
    q(0) <= qa0;
    sclk_t <= buf_clkin;
end Structure;
